### ISSUE TITLE
ASP.NET Web Development Courses to be Completed

### ISSUE THREAD

**Issue by caseynord** [CaseyNord/Treehouse#2]
## TODO

*Courses left to be complete the Treehouse ASP.NET Web Development Track*

* [x] C# Basics
* [x] C# Objects
* [x] Introduction to Visual Studio
* [x] Using GitHub with Visual Studio
* [x] Introduction to HTML and CSS
* [ ] HTTP Basics
* [ ] ASP.NET MVC Basics
* [ ] C# Collections
* [ ] Querying With LINQ
* [ ] Debugging in Visual Studio
* [ ] ASP.NET MVC Forms
* [ ] Package Management With NuGet

:tada: :ok_man: :confetti_ball:

cc @CaseyNord
